jobs:
  linux1:
    name: Build site
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: build the site
      run: make
  linux2:
    name: Deploy website
    runs-on: ubuntu-latest
    needs: [linux1]
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: build the site
      run: make
    - name: deploy site to gh-pages
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: dist
        single-commit: true
